image: gradle:alpine
image: docker:stable


stages:
    - build
    - test
    
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    
before_script:
    - sudo docker login -u $CI_DOCKERHUB_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com/jesscahelen/antenas-integracao/master

build:
  stage: build
  script: 
    - ./gradlew --build-cache build
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew test
