image: gradle:alpine
image: docker:stable


stages:
    - build
    - test
    
variables:
    IMAGE_TAG: antenas-integracao:latest

build:
  stage: build
  script: 
    - ./gradlew --build-cache build
    - sudo docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/jesscahelen/antenas-integracao/master
    - sudo docker build -t $IMAGE_TAG .
    - sudo docker push $IMAGE_TAG
    - sudo docker push projetoantenas/antenas-integracao:latest
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew test
