image: maven:latest

services:
  - docker:dind


stages:
    - build
    - test
    - create-image
    
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  image: maven:latest
  stage: build
  script: 
    - mvn clean install -DskipTests
    
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .m2/repository/
      - build


test:
  image: maven:latest
  stage: test
  script: 
    - $MAVEN_HOME/bin/mvn test


create-image:
  stage: create-image
  services:
  - docker:dind
  script:
    - sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - sudo docker build -t projetoantenas/antenas-integracao .
    - sudo docker push projetoantenas/antenas-integracao
  