image: maven:latest


stages:
    - test
    - build

variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

test:
  stage: test
  script: 
    - $MAVEN_HOME/bin/mvn test

build:
  image: zenika/alpine-maven:latest
  stage: build
  script: 
    - $MAVEN_HOME/bin/mvn clean install -DskipTests 
    - sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - sudo docker build -t projetoantenas/antenas-integracao .
    - sudo docker push projetoantenas/antenas-integracao
    
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .m2/repository/
      - build





  