image: gradle:alpine
image: docker

services:
  - docker:dind

stages:
    - test
    - build
    
test_dind:
    stage: build
    script: 
        - sudo apt-get install -y python3-pip
        - sudo pip3 install --upgrade setuptools
        - sudo pip3 install docker-compose
        - docker-compose build --no-cache
        - docker-compose up -d


build:
  stage: build
  script: ./gradlew --build-cache build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew test
