image: gradle:alpine
image: docker:19.03.1


stages:
    - build
    - test
    
    
before_script:
    - docker login -u $CI_DOCKERHUB_USER -p $CI_DOCKERHUB_PASSWORD $CI_REGISTRY

build:
  stage: build
  services:
    - docker:19.03.1-dind
    
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    
  script: ./gradlew --build-cache build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG

test:
  stage: test
  script: ./gradlew test
