image: gradle:alpine



stages:
    - build
    - test
    
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  script: 
    - ./gradlew --build-cache build
    - sudo docker login -u CI_DOCKERHUB_USER -p CI_DOCKERHUB_PASSWORD registry.gitlab.com/jesscahelen/antenas-integracao/latest
    - sudo docker build -t projetoantenas/antenas-integracao .
    - sudo docker push projetoantenas/antenas-integracao

  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew test
