image: gradle:alpine
image: docker:19.03.1

services:
    - docker:19.03.1-dind

stages:
    - build
    - test
    
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    
before_script:
    - docker login -u $CI_DOCKERHUB_USER -p $CI_DOCKERHUB_PASSWORD $CI_REGISTRY

build:
  stage: build
  script: 
    - ./gradlew --build-cache build
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew test
