image: maven:latest


stages:
    - build
    - test
    - create-image
    
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  script: 
    - /usr/local/apache-maven/bin/mvn clean install -DskipTests 
    
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - .m2/repository/
      - build


test:
  stage: test
  script: 
    - /usr/local/apache-maven/bin/mvn test


create-image:
  image: docker:dind
  stage: create-image
  script:
    - sudo docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - sudo docker build -t projetoantenas/antenas-integracao .
    - sudo docker push projetoantenas/antenas-integracao
  