image: gradle:alpine
image: docker:stable


stages:
    - build
    - test
    
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    
before_script:
    - sudo docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com/jesscahelen/antenas-integracao/master

build:
  stage: build
  script: 
    - ./gradlew --build-cache build
    - sudo docker build -t $IMAGE_TAG .
    - sudo docker push $IMAGE_TAG
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew test
