image: gradle:alpine

services:
    - name: tutum/mongodb:latest

build:
  stage: build
  script: ./gradlew --build-cache build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: docker run -d -p 27017:27017 --name mongodb tutum/mongodb mongod --smallfiles && ./gradlew test
