version: '2'

services:
  app:
    image: projetoantenas/antenas-integracao
    ports: 
      - 8081:8081


  portainer:
     image: portainer/portainer
     ports: 
       - 9000:9000
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
  